services:

  node:
    build: ./
    container_name: node-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf:ro
      - mongo-data:/data/db

  migrate:
    image: node:22
    profiles: ["tools"]
    container_name: migrate
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run migrate

  rollback:
    image: node:22
    profiles: ["tools"]
    container_name: rollback
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run rollback

volumes:
  mongo-data:
