version: '3.9'

services:
  php-apache:
    build: ./php-apache
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mongo

  node:
    build: ./node
    container_name: node-app
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
